on:
  pull_request:
    types: [closed]
    branches:
      - main
      
name: Sonar Scan
jobs:
   sonarqube:
    if: github.event.pull_request.merged == true
    name: inspeccion de codigo
    runs-on: ubuntu-latest
    steps:
    - name: "Example show SonarQube Quality Gate Status value"
      run: echo "Cambio el mensaje"       
