on:
  pull_request:
    types: [closed]
    branches:
      - main
      
name: Sonar Scan
jobs:
   sonarqube:
    name: inspeccion de codigo
    runs-on: ubuntu-latest
    steps:
    - name: "Example show SonarQube Quality Gate Status value"
      run: echo "The Quality Gate status is"       

